package exceptionHandling;
class Resource{
    int power;
    void print(){
        System.out.println("Resource");
    }
}

public class Eg1 {
    int divide(int x, int y, Resource r){
        try {
            int res = x / y;
            if(r.power==1)
                throw new ArrayIndexOutOfBoundsException();
//            r.power=0;
            return res;
        }
        catch(ArithmeticException e){
            System.out.println(e);
//            r.power=0;
            return 0;
        }
        finally{
            System.out.println("Finally block");
            r.power=0;
        }
        //return 0;

    }
    public static void main(String[] args) {
        int x=10;
        int y=10;
        Resource r=new Resource();
        r.power=2;
        int res=new Eg1().divide(x,y,r);
        System.out.println(r.power==0 ? "Resource shut down": "Resource is on");
        System.out.println();

    }
}




package exceptionHandling;
import java.io.*;

public class Eg2 {
    void reading1() throws IOException{
        throw new IOException("File IO not studied");
    }
    void reading2() throws IOException
    {
        reading1();
    }

    public static void main(String[] args) throws IOException{
        new Eg2().reading2();
        System.out.println("Continue the code..");
    }
    
}






package exceptionHandling;
import java.io.*;

public class Eg2 {
    void reading1() throws IOException{
        throw new IOException("File IO not studied");
    }
    void reading2() throws IOException
    {
        reading1();
    }

    public static void main(String[] args){
        try{
            new Eg2().reading2();
        }
        catch(IOException e){
            System.out.println(e);
        }
        
        System.out.println("Continue the code..");
    }
    
}






package exceptionHandling;
import java.io.*;

public class Eg2 {
    void reading1() throws IOException{
        throw new IOException("File IO not studied");
    }
    void dividing1() throws ArithmeticException{
        throw new ArithmeticException();
    }
    void dividing2(){
        dividing1();
    }
    void reading2() throws IOException
    {
        reading1();
    }

    public static void main(String[] args){
        try{
            new Eg2().reading2();
        }
        catch(IOException e){
            System.out.println(e);
        }
        
        System.out.println("Continue the code..");
    }
    
}



package exceptionHandling;
import java.io.*;
class Loan{
    int EMI(int interest, int principle) throws Exception { //propagating Checked Exception
        int emi=0;
        if(interest==0){
            throw new IOException("Interest cannot be zero");
        }
        if(principle==0){
            throw new ClassNotFoundException();
        }
        emi=(interest*principle)/(20*12);
        return emi;
    }

}
class HomeLoan extends Loan{
    @Override
    int EMI(int interest, int principle) throws IOException {
        //Compulsorily propagate same or child Exception
        try {
            return super.EMI(interest, principle);
        }
        catch(Exception e){
            throw new IOException(e.getMessage());
        }
        //return 0;
    }
}
class PersonalLoan extends Loan{
    int EMI(int interest, int principle) throws Exception {
        //Compulsorily propagate same or child Exception
        return super.EMI(interest, principle);
    }
}
class VehicleLoan extends Loan{
    int EMI(int interest, int principle) {
        //Compulsorily propagate same or child or no Exception 
        //return super.EMI(interest, principle);
        return 0;
    }
}
public class Eg3 {

}



